# Generated by Django 4.2.5 on 2023-10-14 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_budgetentry_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetentry',
            name='date',
        ),
        migrations.RemoveField(
            model_name='budgetentry',
            name='recurrence',
        ),
    ]
