# Generated by Django 4.2.5 on 2023-10-19 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_budgetentry_monthlyamount_budgetentry_yearlytimes'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='monthlyPayment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
