# Generated by Django 4.2.5 on 2023-10-19 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_budget_monthlypayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='yearlyIncome',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
